#!/usr/bin/env bash

# Ensure Nginx is running
sudo systemctl start nginx
#Update the Nginx configuration to serve the content on the new port
sed -i "s/8080/80/g" /etc/nginx/sites-available/default
#restart Nginx after updating the configuration
service nginx restart
