#!/usr/bin/env bash
#command that used to fix the issue
#Check Is it actually listening on this port
sudo netstat -lpdn | grep 80
#Update the Nginx configuration to serve the content on the new port
sed -i "s/8080/80/g" /etc/nginx/sites-available/default
#restart Nginx after updating the configuration
service nginx restart
